simulador/src/main/java/com/simulador/mb/PerguntaManagedBean.java
package com.simulador.mb;

import com.simulador.bc.PerguntaBusinessControler;
import com.simulador.pojo.PerguntaPojo;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.ValidatorException;
import java.util.ArrayList;

@ManagedBean
@RequestScoped
public class PerguntaManagedBean {

    protected PerguntaBusinessControler perguntaBC = new PerguntaBusinessControler();

    public PerguntaPojo perguntaPojo;

    public PerguntaManagedBean(){

        perguntaPojo  = new PerguntaPojo();

    }

    public PerguntaPojo getPerguntaPojo() {
        return perguntaPojo;
    }

    public void setPerguntaPojo(PerguntaPojo perguntaPojo) {
        this.perguntaPojo = perguntaPojo;
        System.out.println("Setting PerguntaPojo");
        System.out.println(perguntaPojo.toString() );
    }

    public String addPergunta() {

        System.out.print("addPergunta  inserir ou atualiza -" + '\n' );

        System.out.print(perguntaPojo.toString());

        perguntaBC.inserirPergunta(perguntaPojo);

        FacesMessage doneMessage =  new FacesMessage("Gravou Pergunta com sucesso");

        FacesContext.getCurrentInstance().addMessage(null, doneMessage);
        return "listarPergunta2";
    }

    //public  ArrayList<PerguntaPojo>  getListaPerguntas(){
       // return perguntaBC.pegarListaPerguntas();
  //  }

    public  ArrayList<PerguntaPojo>  getListaPerguntasJPA(){
        return perguntaBC.pegarListaPerguntasJPA();
    }


    
    public void validateEmail(FacesContext context, UIComponent toValidate,
            Object value) throws ValidatorException {
        String emailStr = (String) value;
        if (-1 == emailStr.indexOf("@")) {
            FacesMessage message = new FacesMessage("Invalid email address");
            throw new ValidatorException(message);
        }
    }

    public String editarPergunta(PerguntaPojo perguntaPojo) {

        this.perguntaPojo =  perguntaPojo;

        return "registerPergunta";
    }

    public String excluirPergunta(PerguntaPojo perguntaPojo){

       // this.perguntaPojo =  perguntaPojo;
        System.out.print("Sera excluido" );
        System.out.print(perguntaPojo);

        perguntaBC.removerPergunta(perguntaPojo);

        return "listarPergunta";
    }



    public String editarPergunta() { // usado com com o setPropertyActionListener

        return "registerPergunta";
    }

    public String excluirPergunta() {  // usado com com o setPropertyActionListener

        System.out.print("Sera excluido" );
        System.out.print(perguntaPojo);

        return "listarPergunta";
    }





}

simulador/src/main/webapp/pergunta/listarPergunta.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
<h:head>
  <title>Listar Pergunta</title>
</h:head>
<h:body>
  <h:form>
    <h2>Listar Perguntas - Usa setPropertyActionListener para edição</h2>



      <h:dataTable value="#{perguntaManagedBean.listaPerguntasJPA}" var="pergunta"  >

          <h:column>#{pergunta.id}</h:column>
          <h:column>#{pergunta.pergunta}</h:column>
          <h:column>#{pergunta.complemento}</h:column>
          <h:column>#{pergunta.resposta}</h:column>
          <h:column>#{pergunta.data}</h:column>
          <h:column>#{pergunta.valor}</h:column>

          <h:column>
              <h:commandLink action="#{perguntaManagedBean.editarPergunta()}">
                  Editar
                  <f:setPropertyActionListener
                          value="#{pergunta}"
                          target="#{perguntaManagedBean.perguntaPojo}"
                          />
              </h:commandLink>
          </h:column>

          <h:column>

              <h:commandLink action="#{perguntaManagedBean.excluirPergunta}">
                  Excluir
                  <f:setPropertyActionListener
                          value="#{pergunta}"
                          target="#{perguntaManagedBean.perguntaPojo}"
                          />
              </h:commandLink>
          </h:column>


      </h:dataTable>


    <p><h:commandButton value="Cancel" action="/main" immediate="true" /></p>
  </h:form>
</h:body>
</html>

simulador/src/main/webapp/pergunta/listarPergunta2.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
<h:head>
  <title>Listar Pergunta</title>
</h:head>
<h:body>
  <h:form>
    <h2>Listar Perguntas Editado com Parametros</h2>



      <h:dataTable value="#{perguntaManagedBean.listaPerguntasJPA}" var="pergunta"  >

          <h:column>#{pergunta.id}</h:column>
          <h:column>#{pergunta.pergunta}</h:column>
          <h:column>#{pergunta.complemento}</h:column>
          <h:column>#{pergunta.resposta}</h:column>
          <h:column>#{pergunta.data}</h:column>
          <h:column>#{pergunta.valor}</h:column>

          <h:column>
              <h:commandLink action="#{perguntaManagedBean.editarPergunta(pergunta)}" value="Editar" />
          </h:column>

          <h:column>
              <h:commandLink action="#{perguntaManagedBean.excluirPergunta(pergunta)}" value="Excluir" />
          </h:column>

      </h:dataTable>


    <p><h:commandButton value="Cancel" action="/main" immediate="true" /></p>
  </h:form>
</h:body>
</html>

simulador/src/main/webapp/pergunta/registerPergunta.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
<h:head>
  <title>Registrar Pergunta</title>
</h:head>
<h:body>
  <h:form id="formulario">
    <h2>Simular Perguntas</h2>
    <h4>Formulário de Registro</h4>
    <table border ="1">
        <tr>
            <td>Id</td>
            <td><h:inputText label="Código"
                             id="id" value="#{perguntaManagedBean.perguntaPojo.id}"   />
                <h:message for="id" />
            </td>
        </tr>
      <tr>
        <td>Pergunta</td>
        <td><h:inputText label="Pergunta" id="pergunta" value="#{perguntaManagedBean.perguntaPojo.pergunta}"   required="true"
                       requiredMessage="A pergunta deve ser informada" validatorMessage="O pergunta dever tem no minimo 3 e no máximo 40 caracteres">
            <f:validateLength minimum="3" maximum="40" />
            </h:inputText>


          <h:message for="pergunta" style="color: red"/>
        </td>
      </tr>
      <tr>
        <td>Complemento</td>
        <td><h:inputText label="Complemento"  id="complemento" value="#{perguntaManagedBean.perguntaPojo.complemento}"     required="true"
                         requiredMessage="O complemento deve ser informada " />
          <h:message for="complemento" style="color: red" />
        </td>
      </tr>
      <tr>
        <td>Resposta:</td>
        <td>
          <h:selectOneRadio label="Resposta"  id="resposta" value="#{perguntaManagedBean.perguntaPojo.resposta}"      required="true"
                            requiredMessage="O Valor da resposta deve ser informado " >
            <f:selectItem itemLabel="V" itemValue="V" />
            <f:selectItem itemLabel="F" itemValue="F" />
          </h:selectOneRadio>
          <h:message for="resposta" />
        </td>
      </tr>

        <tr>
            <td>Data:</td>
            <td>
                <h:inputText label="Data" value="#{perguntaManagedBean.perguntaPojo.data}"  required="true" id="data">
                <f:convertDateTime pattern="MM-dd-yy" />
            </h:inputText> (mm-dd-yy)
                <h:message for="data" />
            </td>
        </tr>
      <tr>
        <td>Valor:</td>
        <td>
          <h:selectOneMenu label="Valor"    value="#{perguntaManagedBean.perguntaPojo.valor}">
            <f:selectItem itemLabel="1" itemValue="1" />
            <f:selectItem itemLabel="2" itemValue="2" />
            <f:selectItem itemLabel="3" itemValue="3" />
          </h:selectOneMenu>
        </td>
      </tr>

    </table>

      <p><h:commandButton value="Confirmar Dados"   action="#{perguntaManagedBean.addPergunta}" />
      </p>

    <p><h:commandButton value="Cancel" action="/main" immediate="true" /></p>

  </h:form>
</h:body>
</html>